### ISSUE TITLE
Typing into the JSON body textarea throws console errors

### ISSUE THREAD

**Issue by acburdine** [ianlopshire/adjure#2]
Every time a new character is typed that invalidates the JSON temporarily, a console error is thrown. I think this is being caused by Adjure trying to validate the json every time the json body is changed.

**Comment by acburdine** [comment]
I figured out where the error is occurring. I'll work on a fix for it.

**Comment by acburdine** [comment]
should be fixed in #5

**Comment by ianlopshire** [comment]
closed by #5
